#!/usr/bin/env bash

cd /home/andreas/rrdtool/load
rrdtool graph load.png -t "Load on $(hostname)" -l 0 \
    --legend-position=south --watermark "$(date '+%FT%T')" \
    DEF:load=load.rrd:load:LAST \
    VDEF:l=load,LAST \
    LINE1:load#FF0000:" C" \
    GPRINT:l:"%5.2lf"

cp -p load.png ~/public_html
