#!/usr/bin/env bash
#
#   fill_temp - fills the textfiles with
#               CPU temperature
#
#   2016-03-19   Andreas Dunker   created
#
########################################################################

DUMMY=$@
UNIXTIME=$(date '+%s')
ISOTIME=$(date '+%FT%T')

read TOPIC TEMP <<< $DUMMY
read D HOST FACILITY <<< $(echo $TOPIC | awk -F/ '{printf ("%s %s %s\n", $1, $2, $3)}')
FILENAME=$HOST.$FACILITY.txt

L=$(tail -1 $FILENAME | awk '{print $2}')
DIFF=$(($UNIXTIME-$L))
if [ $DIFF -gt 90 ]
then
    echo "" >> $FILENAME
fi

echo $ISOTIME $UNIXTIME $TEMP >> $FILENAME
exit 0
