#!/usr/bin/env bash
#
#   fill_moni - fills the textfiles with
#               actual values
#
#   2016-03-19   Andreas Dunker   created
#
########################################################################

DUMMY=$@
read TOPIC SUM USED AVAIL <<< $DUMMY
read D HOST FACILITY <<< $(echo $TOPIC | awk -F/ '{printf ("%s %s %s\n", $1, $2, $3)}')
if [ $FACILITY = "df" ]
then
    ./fill_df $DUMMY
elif [ $FACILITY = "temperature" ]
then
    ./fill_temp $DUMMY
fi
exit 0
