#!/usr/bin/env bash
#
#   get_df - gets file system values and puts them
#            into MQTT queue
#
#   2016-03-19   Andreas Dunker   created
#
########################################################################

H=$(hostname)
DF=$(df -k | grep '/dev/root' | awk '{printf ("%d %d %d\n", $2, $3, $4)}')
mosquitto_pub -m "$DF" -t "monitor/$H/df"
exit 0
