#!/usr/bin/env bash

if [ -f bmp280temp.rrd ]
then
    rm -f bmp280temp.rrd
fi
rrdtool create  bmp280temp.rrd --step 60 \
    DS:temperature:GAUGE:120:U:U \
    RRA:AVERAGE:0.5:1:2160       \
    RRA:AVERAGE:0.5:5:2016       \
    RRA:AVERAGE:0.5:15:2880      \
    RRA:AVERAGE:0.5:60:8760      \
    RRA:MIN:0.5:1:2160           \
    RRA:MIN:0.5:5:2016           \
    RRA:MIN:0.5:15:2880          \
    RRA:MAX:0.5:1:2160           \
    RRA:MAX:0.5:5:2016           \
    RRA:MAX:0.5:15:2880

if [ -f bmp280press.rrd ]
then
    rm -f bmp280press.rrd
fi
rrdtool create  bmp280press.rrd --step 60 \
    DS:pressure:GAUGE:120:U:U \
    RRA:AVERAGE:0.5:1:2160       \
    RRA:AVERAGE:0.5:5:2016       \
    RRA:AVERAGE:0.5:15:2880      \
    RRA:AVERAGE:0.5:60:8760      \
    RRA:MIN:0.5:1:2160           \
    RRA:MIN:0.5:5:2016           \
    RRA:MIN:0.5:15:2880          \
    RRA:MAX:0.5:1:2160           \
    RRA:MAX:0.5:5:2016           \
    RRA:MAX:0.5:15:2880

exit 0
