#!/usr/bin/env bash
#
#   graph_db - creates graphics for temperature and pressure
#
#   2016-02-23   Andreas Dunker   created
#
########################################################################
cd /home/andreas/projekte/sensornet/bmp280

tail -1440  bmp280.txt > bmp280_1day.txt
tail -10080 bmp280.txt > bmp280_1week.txt
tail -43200 bmp280.txt > bmp280_1month.txt

for j in *.gp
do
    gnuplot -e "set label \"$(date '+%FT%T')\" at graph 0.01, graph 0.95" $j
done

mv *.png /var/www/html/sensornet/bmp280
exit 0
