#!/usr/bin/env bash
#
#   doit_1min - several things to be run in
#               one minute intervals
#
#   2016-02-23   Andreas Dunker   created
#
########################################################################
/home/andreas/projekte/sensornet/bmp280/baro.py
/home/andreas/projekte/sensornet/monitor/get_df
/home/andreas/projekte/sensornet/monitor/get_temp

exit 0
