#!/usr/bin/env bash
#
#   doit_5min - several things to be run in
#               five minute intervals
#
#   2016-02-23   Andreas Dunker   created
#
########################################################################

/home/andreas/projekte/sensornet/bmp280/graph_bmp280
/home/andreas/projekte/sensornet/monitor/graph_moni
/home/andreas/projekte/sensornet/temphum/graph_temphum
/home/andreas/projekte/sensornet/temphum/graph_volt
/home/andreas/projekte/sensornet/temphum/graph_att

exit 0
