#!/usr/bin/env bash
#
#   doit_5min - several things to be run in
#               five minute intervals
#
#   2016-02-23   Andreas Dunker   created
#
########################################################################

/home/andreas/projekte/sensornet/bmp280/graph_db

for j in coretemp coretemp2 load
do
    /home/andreas/rrdtool/$j/graph_db
done

exit 0
