#!/usr/bin/env bash
#
#   fill_db - fills the databases & textfiles
#
#   2016-03-10   Andreas Dunker   created
#
########################################################################

cd /home/andreas/projekte/sensornet
mosquitto_sub -v -t "#" | while read TOPIC DUMMY
do
    if [ "wohnung/misc/bmp280" = "$TOPIC" ]
    then
        cd bmp280
        ./fill_bmp280 "$DUMMY"
        cd ..
    fi
done

exit 0
