#!/usr/bin/env bash
#
#   fill_db - fills the RRDs with 

cd /home/andreas/projekte/sensornet
mosquitto_sub -v -t "/#" | while read TOPIC DUMMY
do
    if [ "/wohnung/misc/bmp280" = "$TOPIC" ]
    then
        cd bmp280
        read TIME UNIXTIME TEMPERATURE PRESSURE <<< $DUMMY
        rrdtool update bmp280temp.rrd $UNIXTIME:$TEMPERATURE
        rrdtool update bmp280press.rrd $UNIXTIME:$PRESSURE
        cd ..
    fi
done

exit 0
