#!/usr/bin/env bash

export LANG=en_US.UTF-8
cd /home/andreas/rrdtool/coretemp2
D=$(date '+%s')
T=$(/usr/bin/vcgencmd measure_temp | cut -d '=' -f2 | sed 's/..$//')
rrdtool update coretemp2.rrd $D:$T
#echo "rrdtool update coretemp2.rrd $D:$T" >> qqq
