#!/usr/bin/env bash

cd /home/andreas/rrdtool/coretemp2
#rrdtool graph coretemp2.png -t "Temperature on $(hostname)" -l 0 \
rrdtool graph coretemp2.png -t "Temperature on $(hostname)" \
    --legend-position=south --watermark "$(date '+%FT%T')"       \
    DEF:temp=coretemp2.rrd:temp:LAST LINE1:temp#00FF00:"C"       \
    DEF:avg=coretemp2.rrd:temp:AVERAGE LINE1:avg#FF0000:"avg C"

mv coretemp2.png ~/public_html
