" a vimrc with nice stuff

colorscheme andreas

set autoindent
set background=light
set expandtab           " no tabs please
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set listchars=tab:>-,trail:~,eol:<,extends:>
set nobackup            " no wimp, no backup
set nowrap              " don't mess screen with wrapped lines
set number              " line numbers for orientation
set ruler
set scrolloff=999       " holds active line in the middle of the screen
set shiftwidth=4        " autoindent with 4 spaces
set showcmd
set showmatch
set showmode
set smartcase           " handling upper case searching
set statusline=%t%a\ buf_no:\ %n\ %w%m%r\ %{v:register}\ %=[%{strlen(&ft)?&ft:'no\ filetype'}]\ %l\/%L:%c\ %p%%\ (0x%B)\ 
set softtabstop=4
set visualbell
syntax on

imap ,, <ESC>           " leave fingers on keys
" EOF
